/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author varga
 */
public class FejlecPanel extends javax.swing.JPanel {
    private Image kep=new ImageIcon(this.getClass().getResource("/kepek/facebookfej.jpg")).getImage();
    private final int SZELESSEG=750;
    private final int MAGASSAG=40;
    /**
     * Creates new form FejlecPanel
     */
    public FejlecPanel() {
        initComponents();
        setSize(kep.getWidth(this), kep.getHeight(this));
        repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(kep,0, 0, this);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtKeresett = new javax.swing.JTextArea();
        btnKeres = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(750, 40));
        setMinimumSize(new java.awt.Dimension(750, 40));
        setPreferredSize(new java.awt.Dimension(750, 40));

        txtKeresett.setColumns(20);
        txtKeresett.setRows(5);
        jScrollPane1.setViewportView(txtKeresett);

        btnKeres.setText("Keresés");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnKeres, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnKeres, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeres;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtKeresett;
    // End of variables declaration//GEN-END:variables
}
