/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feluletek;

import alaposztalyok.Felhasznalo;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import vezerles.Global;
import vezerles.Vezerlo;

/**
 *
 * @author varga
 */
public class KozossegiPanel extends javax.swing.JPanel {

    private final int SZELESSEG = 600;
    private final int MAGASSAG = 450;
    private Vezerlo vezerlo;

    private List<Felhasznalo> felhasznaloLista = new ArrayList<>();
    private String kepEleres = Global.KOZOSSEGIKEP_ELERES;

    public void setVezerlo(Vezerlo vezerlo) {
        this.vezerlo = vezerlo;
    }

    //Képet beállítom és átméretezem a panel méretére, hogy kitöltse.
    private Image kep = new ImageIcon(this.getClass().getResource(kepEleres)).getImage().getScaledInstance(SZELESSEG, MAGASSAG, 1);

    /**
     * Creates new form KozossegiPanel
     */
    public KozossegiPanel() {
        initComponents();
        beallitas();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        g.drawImage(kep, 0, 0, this);
        vezerlo.uzenetRajzolas(g);
        if (vezerlo != null) {
            for (Felhasznalo felhasznalo : felhasznaloLista) {
                vezerlo.felhasznaloRajzolas(felhasznalo, g);
                if(felhasznalo.isKijeloltek()){
                    g.drawImage(felhasznalo.getKijeloltKep(), felhasznalo.getX(), felhasznalo.getY(), this);
                }
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        if (vezerlo != null) {
            vezerlo.pozicioKeres(evt.getX(), evt.getY());
        }
        repaint();
    }//GEN-LAST:event_formMousePressed

    private void beallitas() {
        setSize(SZELESSEG, MAGASSAG);

    }

    public void setFelhasznaloLista(List<Felhasznalo> felhasznaloLista) {
        this.felhasznaloLista = felhasznaloLista;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
